<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-M3BBU8N8" failures="1" tests="2" name="Test" time="5.141" errors="0" timestamp="2020-10-20T11:28:51 IST">
  <testcase classname="restAPITest.testRunner" name="SoapTest" time="4.616"/>
  <testcase classname="restAPITest.testRunner2" name="individual_testcase" time="0.471">
    <failure type="java.lang.AssertionError" message="expected [FAILED] but found [FINISHED]">
      <![CDATA[java.lang.AssertionError: expected [FAILED] but found [FINISHED]
at restAPITest.testRunner2.individual_testcase(testRunner2.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- individual_testcase -->
</testsuite> <!-- Test -->
